# Generated by Django 3.2.13 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(default=0, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
