# Generated by Django 3.2.13 on 2022-04-28 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20220428_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
