# Generated by Django 3.2.13 on 2022-05-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_candidate_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
