# Generated by Django 3.2.13 on 2022-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20220503_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='datetime',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
