# Generated by Django 3.2.13 on 2022-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20220504_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='votingstatus',
            field=models.CharField(default='Enable', max_length=100),
        ),
    ]
